[FT-191] Add new settings screen
1Coin-FinanceTracker/1CoinClient pull request #5
Opened 2023-01-24 15:39 UTC by Bittner322

2023-01-24 16:21 UTC, VitalyPeryatin requested changes

2023-01-24 16:21 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsScreen.kt
> +        Column(
Давай добавим скролл по вертикали для `Column`. В будущем будут добавляться новые items в настройках, и на маленьких устройствах не будет помещаться

2023-01-24 16:21 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsScreen.kt
> +                userEmail = userEmail.value
`userEmail` наверняка будет подгружаться асинхронно из файла или сети, поэтому здесь должна быть подписка на состояние через `.collectAsState()`

2023-01-24 16:21 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsScreen.kt
> +                color = CoinTheme.color.content.copy(TextColorFloat)
`.copy(TextColorFloat)` -> `.copy(alpha = TextColorFloatAlpha)`

2023-01-24 16:21 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsScreen.kt
> +                color = CoinTheme.color.content.copy(TextColorFloat)
`.copy(TextColorFloat)` -> `.copy(alpha = TextColorFloatAlpha)`

2023-01-24 16:21 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsScreen.kt
> +                color = CoinTheme.color.content.copy(TextColorFloat)
`.copy(TextColorFloat)` -> `.copy(alpha = TextColorFloatAlpha)`

2023-01-24 16:21 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/SettingsScreen.kt
> +            Spacer(modifier = Modifier.weight(1f))
При добавлении скролла оставить `Spacer(modifier = Modifier.weight(1f))` не получится скорее всего. Но если версия будет не в самом низу экрана - ничего страшного. Она должна скролиться вместе со всем контентом. 

И попробуй добавить много повторяющихся items в настройки и посмотреть на сколько корректное поведение экрана при скролле

2023-01-24 16:21 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/views/SettingsMyProfileItem.kt
> +    val isUserAuthorized = userEmail != ""
`isUserAuthorized` лучше определять на уровне `ViewModel`, так как это относится к логике отоюражения данных (нужно произвести некую логику, чтобы вычислить значение этого флажка). Флажок `isUserAuthorized` можем передаваться в `SettingsMyProfileItem` отдельным параметром

2023-01-24 16:21 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/presentation/settings/views/SettingsMyProfileItem.kt
> +                    .clickable {  }
Тут было бы логично сделать так, чтобы если пользователь не был авторизован, кликабелен был бы весь элемент. А если авторизован, то кликабельна была бы только кнопка выхода

2023-01-25 15:11 UTC, Bittner322 commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/di/MainModule.kt
> +    settingsScreenModule,
settingsModule уже существует

2023-01-25 15:26 UTC, VitalyPeryatin requested changes

2023-01-25 15:26 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/di/MainModule.kt
> +    settingsScreenModule,
Давай тогда уже существующие `settingsModule` переименуем в `settingsCacheModule`, а `settingsScreenModule` переименуем в `settingsModule`? 
Кажется, что так было бы логично

2023-01-25 16:05 UTC, VitalyPeryatin requested changes

2023-01-25 16:05 UTC, VitalyPeryatin commented on common/src/commonMain/resources/MR/base/strings.xml
> +    <string name="settings_topbar_text">Settings</string>
В этом файле трижды повторяется раздел `<!-- Settings -->`

2023-01-25 16:05 UTC, VitalyPeryatin commented on common/src/commonMain/resources/MR/ru/strings.xml
> +    <string name="settings_topbar_text">Настройки</string>
В этом файле дважды повторяется раздел `<!-- Settings -->`

2023-01-25 16:24 UTC, VitalyPeryatin approved these changes

2023-01-25 16:24 UTC, merged