FEATURE [FT-224]: Viewmodel ComposeScreen wrapper
1Coin-FinanceTracker/1CoinClient pull request #61
Opened 2023-03-14 11:11 UTC by maltsev-gorskij

- Refactored common module config to a more concise style
- In all screens replaced StoredViewModel with ComposeScreen
- In all Composable calls up the stack, deleted wrapping calls with CoinTheme composable function
- Added git hook for verifying branch name by "valid_branch_regex" pattern in pre-commit hook. Branch name must be like "branch_type/JIRAPREFIX-TICKETNUMBER_branch_name"
- Added git hook for adding ticket name, parsed from branch name, to commit message. All commits will be prepended with [FT-123] test with ticket number

2023-03-17 16:58 UTC, VitalyPeryatin requested changes

2023-03-17 16:58 UTC, VitalyPeryatin commented on hooks/prepare-commit-msg
> +# search jira issue id in a pattern such a "feature/ABC-123-description"
We have other pattern of branch naming: `ABC-123_description`. And there is no strict rules about branch naming. I'm not sure about adding such strict rules

2023-03-18 06:39 UTC, maltsev-gorskij commented on buildSrc/src/main/kotlin/android-setup.gradle.kts
> +    namespace = "com.finance_tracker.finance_tracker.common"
This is a convention plugin, which is applied only in build.gradle.kts of common module, modifying its namespace only. Working this way, plugin cannot affect namespaces of android or other modules

2023-03-18 06:53 UTC, maltsev-gorskij commented on hooks/prepare-commit-msg
> +# search jira issue id in a pattern such a "feature/ABC-123-description"
It is not some kind of rule. Its just regexp pattern for checking if commit message already has ticket name. 
Added detailed comments to this hooks script for better understanding of its logic

2023-03-18 13:10 UTC, VitalyPeryatin commented on buildSrc/src/main/kotlin/android-setup.gradle.kts
> +    namespace = "com.finance_tracker.finance_tracker.common"
Got it, but I think it's risky to namespace in convention plugins because somebody in future can accidentally use `android-setup` in other android modules

2023-03-18 13:19 UTC, maltsev-gorskij commented on buildSrc/src/main/kotlin/android-setup.gradle.kts
> +    namespace = "com.finance_tracker.finance_tracker.common"
Moved namespace declaration to build.gradle.kts of common module

2023-03-18 13:52 UTC, VitalyPeryatin approved these changes

2023-03-18 13:52 UTC, merged