[FT-241] Add plans tab and budgets widget
1Coin-FinanceTracker/1CoinClient pull request #84
Opened 2023-05-08 12:46 UTC by Bittner322

2023-05-08 12:49 UTC, Bittner322 commented
<img width="447" alt="Снимок экрана 2023-05-08 в 18 44 27" src="https://user-images.githubusercontent.com/100136541/236828331-15cb3046-8510-406b-9283-8063e97fd969.png">
<img width="475" alt="Снимок экрана 2023-05-08 в 18 43 24" src="https://user-images.githubusercontent.com/100136541/236828350-00e8f69a-f6f8-4038-8d6a-69400c86d9f9.png">

https://user-images.githubusercontent.com/100136541/236828358-2a026b01-6791-466f-9372-32e8ddf8aee6.mp4

2023-05-09 07:31 UTC, VitalyPeryatin requested changes

2023-05-09 07:31 UTC, VitalyPeryatin commented on common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/plans/views/BudgetByCategoriesWidget.kt
> +                        } else if (budgets.size > MaxBudgetsBeforeUncoverWidget && !expanded) {
Is it possible to simplify this if-else statement to this one?
```
items(
    items = if (expanded) {
        budgets
    } else {
        budgets.take(MaxBudgetsBeforeUncoverWidget)
    }
) { budget ->
    BudgetCard(budget)
}
```

2023-05-09 07:31 UTC, VitalyPeryatin commented on common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/plans/views/BudgetByCategoriesWidget.kt
> +                                .size(38.dp)
Size of this icon on design is `24.dp`

2023-05-09 07:31 UTC, VitalyPeryatin commented on common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/plans/views/BudgetByCategoriesWidget.kt
> +                        Icon(
Let's animatedly rotate the icon 180 degrees when `expanded = true`

2023-05-09 07:31 UTC, VitalyPeryatin commented on common/src/commonMain/resources/MR/files/ic_plans_active.svg
Icons in resources should be black by default

2023-05-09 07:31 UTC, VitalyPeryatin commented on common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/BudgetCard.kt
> +            Modifier
Could you add name of this parameter: `modifier = ...`

2023-05-09 07:31 UTC, VitalyPeryatin commented on common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/BudgetCard.kt
> +            Row {
If you add parameter `verticalAlignment = Alignment.CenterVertically` in the `Row`, code will be safer relatively UI stability

2023-05-09 07:31 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/models/Budget.kt
> +    val spentAmount: Double,
It would be more convenient if types of `spentAmount` and `limitAmount` were `Amount` instead of `Double`, because later you need to take into account the currency, user localization and reduction of large numbers

2023-05-09 07:31 UTC, VitalyPeryatin commented on common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/BudgetCard.kt
> +                progress = (budget.spentAmount / budget.limitAmount).toFloat()
If `limitAmount` is 0, application will crash. You need handle case with `limitAmount = 0` separately and show `progress = 1f`

2023-05-09 07:31 UTC, VitalyPeryatin commented on common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/BudgetCard.kt
> +                    text = "$${budget.spentAmount}/$${budget.limitAmount}",
Try use `Amount.format` function for showing amount with currency. Try not to hardcode currency `$`

2023-05-09 07:31 UTC, VitalyPeryatin commented on common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/BudgetCard.kt
> +                Text(
Let`s divide this `Text` into 3 `Text`s: 
- For `spentAmount`
- For symbol `/`
- For `limitAmount`

In such case you can correctly handle big numbers and set max width of `Text`s

2023-05-09 07:31 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/plans/PlansScreenViewModel.kt
> +class PlansScreenViewModel: BaseViewModel<PlansAction>() {
Just `PlansViewModel`

2023-05-12 18:23 UTC, VitalyPeryatin approved these changes

2023-05-12 19:04 UTC, merged