[FT-260] Setting up a project for the M1 Pro
1Coin-FinanceTracker/1CoinClient pull request #92
Opened 2023-05-13 17:11 UTC by eldaroid

2023-05-13 17:27 UTC, VitalyPeryatin requested changes

2023-05-13 17:27 UTC, VitalyPeryatin commented on generateIOS.sh
> +        echo 'export JAVA_HOME="$HOMEBREW_PREFIX/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home"' >> ~/.zshrc
We need to check if `JAVA_HOME` exists in `.zshrc` because current script can break ready-made environment

2023-05-13 17:27 UTC, VitalyPeryatin commented on generateIOS.sh
> +        sudo ln -sfn $HOMEBREW_PREFIX/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk &&
We need to install `java11` only if there isn't `JAVA_HOME` in `.zshrc`

2023-05-13 17:27 UTC, VitalyPeryatin commented on generateIOS.sh
> +./gradlew generateDummyFramework &&
Is  `&&` redundant?

2023-05-13 17:27 UTC, VitalyPeryatin commented on generateIOS.sh
> +## Steps documentation in Notion: https://regal-bone-e41.notion.site/iOS-1Coin-93a26d9be65e491c86b390f0f2448aae
Could you update link to Notion doc on actual 1Coin docs in Notion?

2023-05-13 17:30 UTC, maltsev-gorskij commented on generateIOS.sh
> +        brew install java11 &&
Be sure to try to remove jdk11 installed with brew and appropriate symbolic link from system and rerun script freshly and make sure it work well.

2023-05-13 17:34 UTC, maltsev-gorskij commented on generateIOS.sh
> +./gradlew generateDummyFramework &&
Nope. According to bash doc it means that pod install will only run if previous command is success. So && will show gradle error and just simply will not run pod install and show appropriate error

2023-05-13 17:35 UTC, maltsev-gorskij commented on generateIOS.sh
> +./gradlew generateDummyFramework &&
https://stackoverflow.com/questions/4510640/what-is-the-purpose-of-in-a-shell-command

Description of && can be found here with examples

2023-05-14 07:29 UTC, VitalyPeryatin approved these changes

2023-05-15 08:04 UTC, maltsev-gorskij approved these changes

2023-05-16 04:56 UTC, merged