Add Snackbars
1Coin-FinanceTracker/1CoinClient pull request #93
Opened 2023-05-20 13:12 UTC by VitalyPeryatin

https://github.com/1Coin-FinanceTracker/1CoinClient/assets/22561563/355c38f9-36de-49fe-b167-0becf0eab799

2023-05-29 20:30 UTC, Bittner322 approved these changes

2023-05-30 04:36 UTC, merged

2023-05-30 14:36 UTC, maltsev-gorskij requested changes

2023-05-30 14:36 UTC, maltsev-gorskij commented on common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/ComposeScreen.kt
> +            CompositionLocalProvider(LocalCoinSnackbarHostState provides snackbarHostState) {
Do you even need this CompositionLocal as it used for now only in exactly one place - CoinSnackbarHost?

You can pass snackbarHostState directly in CoinSnackbarHost without CompositionLocal and remove snackbar logic from handleAction method in favor of ViewModel extentions only. 

Overall your SnackbarManager approach allows to manage snackbar in two places. 
- ViewModel extension showCurrentScreenSnackbar and else
- handleAction method with baseLocalsStorage contans CoinSnackbarHostState.handleSnackbarState method

I cant figure out when mixing two approaches will be better than maintaining one for all screen. 

Think of this one. One screen will show toast in handleAction, second screen will call ViewModel extentions and modify snackbar state via manipulating with SnackbarManager. 

Just for thinking, if i understand api right, maybe will be better to remain one way of doing it and simplify the api and future support.

2023-05-30 16:32 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/interactors/transactions/TransactionsInteractor.kt
> +    fun getTransactionsSizeUpdates(): Flow<Unit> {
Fixed

2023-05-30 16:32 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/interactors/transactions/TransactionsInteractor.kt
> +    fun getTransactionsByAccountIdSizeUpdates(id: Long): Flow<Unit> {
Fixed

2023-05-30 16:36 UTC, VitalyPeryatin commented on common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/interactors/transactions/GetTransactionsForChartUseCase.kt
> +    suspend fun invoke(
I don't like `operator fun invoke()` functions, because the make code less readable in the place of using this function such as `someUseCase()`. 
Moreover as far as I know we can't use `operator` with `suspend` functions. Let's leave it as it is

2023-05-30 16:39 UTC, VitalyPeryatin commented on common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/core/navigation/NavControllerExt.kt
> +inline fun <reified T> RootController.setScreenResult(block: T.() -> Unit) {
Yeah, I know. Thank you for the comment! 
We can't use FragmentResult API because we use Odyssey library, so I decided to write this function for returning result, because I've found it very comfortable for using for the future

2023-05-30 16:39 UTC, VitalyPeryatin commented on common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/snackbar/CoinSnackbarHostState.kt
> +    fun dismiss() {
Fixed

2023-05-30 16:41 UTC, VitalyPeryatin commented on common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/ComposeScreen.kt
> +            CompositionLocalProvider(LocalCoinSnackbarHostState provides snackbarHostState) {
I thought about it the same way, but I was afraid to delete this API. Let's see a little bit how we will work with Snackbars and make a decision about deletion later on

2023-05-30 16:42 UTC, maltsev-gorskij commented on common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/ComposeScreen.kt
> +            CompositionLocalProvider(LocalCoinSnackbarHostState provides snackbarHostState) {
Yep. Agreed with that. Let it be and watch which way will be most comfortable to use.